# Generated by Django 4.2.7 on 2025-12-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Название книги")),
                ("author", models.CharField(max_length=200, verbose_name="Автор")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cover_image/%Y/%m/%d/", verbose_name="Изображение обложки"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("year_published", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Год издания")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("AVAILABLE", "Available"), ("READS", "Reads"), ("IN_ARCHIVE", "In Archive")],
                        default="AVAILABLE",
                        max_length=10,
                        verbose_name="Статус книги",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="13-digit ISBN number",
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "list_type",
                    models.CharField(
                        choices=[("WANT_TO_READ", "Want To Read"), ("READING", "Reading"), ("READ", "Read")],
                        max_length=12,
                        verbose_name="Тип списка",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_lists",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список чтения",
                "verbose_name_plural": "Списки чтения",
                "ordering": ["-created_at"],
            },
        ),
    ]
